name       : yasm
version    : 1.3.0
release    : 6
source     :
    - https://github.com/yasm/yasm/archive/v1.3.0.tar.gz : f708be0b7b8c59bc1dbe7134153cd2f31faeebaa8eec48676c10f972a1f13df3
license    : GPL-2.0-or-later
component  : programming.tools
summary    : Rewrite of the NASM assembler
description: |
    Yasm is a complete rewrite of the NASM-2.10.07 assembler. It supports the x86 and AMD64 instruction sets, accepts NASM and GAS assembler syntaxes and outputs binary, ELF32 and ELF64 object formats.
emul32     : yes
patterns   :
    - /*
setup      : |
    %reconfigure
build      : |
    %make
install    : |
    %make_install
