name        : yasm
version     : 1.2.0
release     : 3
source      :
    - http://www.tortall.net/projects/yasm/releases/yasm-1.2.0.tar.gz : 768ffab457b90a20a6d895c39749adb547c1b7cb5c108e84b151a838a23ccf31
license     : GPL-2.0
component   : programming.tools
summary     : Rewrite of the NASM assembler
description : |
    Yasm is a complete rewrite of the NASM-2.10.07 assembler. It supports the x86 and AMD64 instruction sets, accepts NASM and GAS assembler syntaxes and outputs binary, ELF32 and ELF64 object formats.
emul32     : yes
patterns   :
    - /*
builddeps  :
    - glibc-32bit-devel
    - libgcc-32bit
setup      : |
    sed -i 's#) ytasm.*#)#' Makefile.in
    %configure
build      : |
    %make
install    : |
    %make_install
